### ISSUE TITLE
getting all textures that are visible

### ISSUE THREAD

**Issue by SinemSemsioglu** [eliemichel/MapsModelsImporter-samples#4]
Hi! I am trying to export a Google Earth model while a .kml file is being displayed. I see the .kml file output (a route) in RenderDoc's TextureViewer but it doesn't show up in Blender when I import. Is there any way to configure the imported textures?

**Comment by eliemichel** [comment]
There is no solution for this with the add-on as is. It tries to recognize from the capture something that looks like a google maps rendering but then anything other than this is ignored (because the capture also include things related to drawing the UI, the heads up labels etc.) You can look into google_map.py in the add-on to hack on it and extract whatever more you need but it'll get technical I must warn you. ^^
